packages:
  - playground
  - docs
  - packages/**/*
  - examples/**/*
catalogs:
  bundler:
    esbuild-plugin-globals: ^0.2.0
    tsup: 6.6.0
    unbuild: ^3.5.0
    unplugin-vue-jsx: ^0.6.1
  cli:
    '@antfu/eslint-config': ^4.2.1
    '@antfu/ni': ^23.3.1
    bumpp: ^10.0.3
    eslint: ^9.20.1
    lint-staged: ^15.4.3
    pnpm: ^10.4.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.2
    typescript: ^5.7.3
    vite: ^6.1.0
  docs:
    '@iconify-json/svg-spinners': ^1.2.2
    '@shikijs/vitepress-twoslash': ^2.3.2
    '@vitejs/plugin-vue-jsx': ^4.1.2
    floating-vue: ^5.2.2
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.2
    vitepress-plugin-demo: ^0.8.0
    vitepress-plugin-group-icons: ^1.3.5
  share:
    '@vueuse/core': ^13.0.0
    naive-ui: ^2.41.0
    unplugin-auto-import: ^0.16.4
    unplugin-vue-components: ^28.1.0
    vue: ^3.5.13
  tesing:
    vitest: ^3.0.5
  types:
    '@types/node': ^22.13.4
  utils:
    '@hairy/utils': ^1.33.0
    defu: ^6.1.4
    nanoid: ^5.1.5
