packages:
  - playground
  - docs
  - packages/**/*
  - examples/**/*
catalogs:
  bundler:
    esbuild-plugin-globals: ^0.2.0
    tsup: 6.6.0
    unbuild: ^3.5.0
    unplugin-vue-jsx: ^0.6.1
  cli:
    '@antfu/eslint-config': ^4.16.2
    '@antfu/ni': ^23.3.1
    bumpp: ^10.2.0
    eslint: ^9.30.1
    lint-staged: ^15.5.2
    pnpm: ^10.12.4
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    vite: ^7.0.3
  docs:
    '@iconify-json/svg-spinners': ^1.2.2
    '@shikijs/vitepress-twoslash': ^3.7.0
    '@vitejs/plugin-vue-jsx': ^5.0.1
    floating-vue: ^5.2.2
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.8
    vitepress-plugin-demo: ^0.8.0
    vitepress-plugin-group-icons: ^1.6.1
  share:
    '@vueuse/core': ^13.5.0
    naive-ui: ^2.42.0
    unplugin-auto-import: ^0.16.7
    unplugin-vue-components: ^28.8.0
    vue: ^3.5.17
  tesing:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.0.11
  utils:
    '@hairy/utils': ^1.33.0
    defu: ^6.1.4
    nanoid: ^5.1.5
