/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const defineActions: typeof import('naive-ultra')['defineActions']
  const defineForm: typeof import('naive-ultra')['defineForm']
  const defineTable: typeof import('naive-ultra')['defineTable']
  const field: typeof import('naive-ultra')['field']
  const useColumnIndexes: typeof import('naive-ultra')['useColumnIndexes']
  const useColumnLink: typeof import('naive-ultra')['useColumnLink']
  const useColumns: typeof import('naive-ultra')['useColumns']
}
