/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const defineControls: typeof import('naive-ui-pro-components')['defineControls']
  const defineForm: typeof import('naive-ui-pro-components')['defineForm']
  const defineTable: typeof import('naive-ui-pro-components')['defineTable']
  const field: typeof import('naive-ui-pro-components')['field']
  const useColumnIndexes: typeof import('naive-ui-pro-components')['useColumnIndexes']
  const useColumnLink: typeof import('naive-ui-pro-components')['useColumnLink']
  const useColumns: typeof import('naive-ui-pro-components')['useColumns']
}
