/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NpActions: typeof import('naive-ultra')['NpActions']
    NpCheckboxGroup: typeof import('naive-ultra')['NpCheckboxGroup']
    NpForm: typeof import('naive-ultra')['NpForm']
    NpRadioGroup: typeof import('naive-ultra')['NpRadioGroup']
    NpTable: typeof import('naive-ultra')['NpTable']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
  }
}
