/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NuActions: typeof import('naive-ultra')['NuActions']
    NuCheckboxGroup: typeof import('naive-ultra')['NuCheckboxGroup']
    NuForm: typeof import('naive-ultra')['NuForm']
    NuRadioGroup: typeof import('naive-ultra')['NuRadioGroup']
    NuTable: typeof import('naive-ultra')['NuTable']
  }
}
